# Generated by Django 4.2.1 on 2023-06-01 19:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("agent_managment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="agent",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="vector_index_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
