# Generated by Django 4.2.2 on 2023-06-07 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent_managment', '0002_agent_created_agent_updated_agent_vector_index_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agent',
        ),
    ]
