# Generated by Django 4.2.1 on 2023-06-07 20:24

import bmw_llm_dms.common.utils.user_utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("agent_managment", "0004_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=bmw_llm_dms.common.utils.user_utils.get_standard_user,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
