# Generated by Django 4.2.1 on 2023-06-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent_managment", "0005_alter_agent_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="name",
            field=models.CharField(default="agentname", max_length=200),
            preserve_default=False,
        ),
    ]
