# Generated by Django 4.2.2 on 2023-06-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent_managment", "0006_agent_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="chatbot_api_url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="chatbot_frontend_url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
