# Generated by Django 4.2.2 on 2023-06-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent_managment", "0007_agent_chatbot_api_url_agent_chatbot_frontend_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="greeting",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
