# Generated by Django 4.2.2 on 2023-06-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent_managment", "0008_agent_greeting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="greeting",
            field=models.CharField(
                blank=True, default="Hi, how can I help you?", max_length=200, null=True
            ),
        ),
    ]
