# Generated by Django 4.2.2 on 2023-06-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent_managment", "0009_alter_agent_greeting"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="deployment_status",
            field=models.IntegerField(
                choices=[(1, "Pending"), (2, "Deployed"), (3, "Failed")], default=1
            ),
        ),
    ]
