# Generated by Django 4.2.2 on 2023-06-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent_managment", "0010_agent_deployment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="metadata",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
