# Generated by Django 4.2.2 on 2023-09-28 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0001_initial'),
        ('agent_managment', '0011_agent_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prompts.prompt'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
