# Generated by Django 4.2.1 on 2023-06-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_managment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="uploaded_file",
            field=models.FileField(default=None, upload_to="files/"),
            preserve_default=False,
        ),
    ]
