# Generated by Django 4.2.1 on 2023-06-01 19:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("file_managment", "0003_alter_file_location_id_alter_file_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="file",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
