# Generated by Django 4.2.2 on 2023-06-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_managment', '0004_file_created_file_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
