# Generated by Django 4.2.2 on 2023-06-07 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent_managment', '0003_delete_agent'),
        ('file_managment', '0005_files'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
