# Generated by Django 4.2.2 on 2023-06-13 14:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agent_managment", "0011_agent_metadata"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("file_managment", "0010_alter_file_user_id"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="File",
            new_name="DocumentFile",
        ),
    ]
